### ISSUE TITLE
Cannot finish setup

### ISSUE THREAD

**Issue by Alberto2K** [grafana/tutorial-environment#6]
Second time to run this demo on my mac and got the following error when I tried to execute the docker-compose:

Building app
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 362, in ensure_image_exists
  File "compose/service.py", line 1125, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 311, in get_all_credentials
  File "site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
[7458] Failed to execute script docker-compose

**Comment by marcusolsson** [comment]
It looks like it's trying to access your credentials for the Google Cloud registry. I think this is related to local configuration. Do you have gcloud installed on your machine?

**Comment by Alberto2K** [comment]
No, I don't have it. Only AWS CLI

**Comment by marcusolsson** [comment]
Unfortunately, I'm not able to reproduce this. Could you share some details on what OS and Docker version you're running?
